// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinerKlinik.Data;

#nullable disable

namespace VeterinerKlinik.Migrations
{
    [DbContext(typeof(VeterinerKlinikContext))]
    [Migration("20260203144349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Hayvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HayvanTipi")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Hayvanlar");

                    b.HasDiscriminator<string>("HayvanTipi").HasValue("Hayvan");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Muayene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teshis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VeterinerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.HasIndex("VeterinerId");

                    b.ToTable("Muayeneler");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VeterinerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.HasIndex("VeterinerId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Veteriner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzmanlikAlani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veterinerler");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Kedi", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.Property<string>("IrkTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kedi");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Kopek", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.Property<string>("Cins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Kopek");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Kus", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.Property<bool>("KonusabiliyorMu")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Kus");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Hayvan", b =>
                {
                    b.HasOne("Musteri", "Musteri")
                        .WithMany("Hayvanlar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Muayene", b =>
                {
                    b.HasOne("VeterinerKlinik.Models.Hayvan", "Hayvan")
                        .WithMany()
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinerKlinik.Models.Veteriner", null)
                        .WithMany("Muayeneler")
                        .HasForeignKey("VeterinerId");

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Randevu", b =>
                {
                    b.HasOne("VeterinerKlinik.Models.Hayvan", "Hayvan")
                        .WithMany()
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeterinerKlinik.Models.Veteriner", null)
                        .WithMany("Randevular")
                        .HasForeignKey("VeterinerId");

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("Musteri", b =>
                {
                    b.Navigation("Hayvanlar");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Veteriner", b =>
                {
                    b.Navigation("Muayeneler");

                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
