// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinerKlinik.Models;

#nullable disable

namespace VeterinerKlinik.Migrations
{
    [DbContext(typeof(VeterinerKlinikContext))]
    [Migration("20260414115128_SeedVerileriniSil")]
    partial class SeedVerileriniSil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VeterinerKlinik.Models.Hayvan", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanTipi")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hayvanlar");

                    b.HasDiscriminator<string>("HayvanTipi").HasValue("Hayvan");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Muayene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teshis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.ToTable("Muayeneler");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hastalik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanCinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HayvanTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tedavi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VeterinerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeterinerId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Veteriner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UzmanlikAlani")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Veterinerler");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.CiftlikHayvani", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.HasDiscriminator().HasValue("Çiftlik");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.EgzotikHayvan", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.HasDiscriminator().HasValue("Egzotik");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.EvcilHayvan", b =>
                {
                    b.HasBaseType("VeterinerKlinik.Models.Hayvan");

                    b.HasDiscriminator().HasValue("Evcil");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Muayene", b =>
                {
                    b.HasOne("VeterinerKlinik.Models.Hayvan", "Hayvan")
                        .WithMany()
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Randevu", b =>
                {
                    b.HasOne("VeterinerKlinik.Models.Veteriner", "Veteriner")
                        .WithMany("Randevular")
                        .HasForeignKey("VeterinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veteriner");
                });

            modelBuilder.Entity("VeterinerKlinik.Models.Veteriner", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
